---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: hcloudremediationtemplates.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: HCloudRemediationTemplate
    listKind: HCloudRemediationTemplateList
    plural: hcloudremediationtemplates
    shortNames:
    - hcrt
    - hcremediationtemplate
    - hcremediationtemplates
    - hcloudrt
    - hcloudremediationtemplate
    singular: hcloudremediationtemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Type of the remediation strategy
      jsonPath: .spec.template.spec.strategy.type
      name: Strategy
      type: string
    - description: How many times remediation controller should attempt to remediate
        the node
      jsonPath: .spec.template.spec.strategy.retryLimit
      name: Retry limit
      type: string
    - description: Timeout for the remediation
      jsonPath: .spec.template.spec.strategy.timeout
      name: Timeout
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: HCloudRemediationTemplate is the Schema for the hcloudremediationtemplates
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HCloudRemediationTemplateSpec defines the desired state of
              HCloudRemediationTemplate.
            properties:
              template:
                description: HCloudRemediationTemplateResource describes the data
                  needed to create a HCloudRemediation from a template.
                properties:
                  spec:
                    description: Spec is the specification of the desired behavior
                      of the HCloudRemediation.
                    properties:
                      strategy:
                        description: Strategy field defines remediation strategy.
                        properties:
                          retryLimit:
                            description: Sets maximum number of remediation retries.
                            type: integer
                          timeout:
                            description: Sets the timeout between remediation retries.
                            type: string
                          type:
                            default: Reboot
                            description: Type of remediation.
                            type: string
                        required:
                        - timeout
                        type: object
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
          status:
            description: HCloudRemediationTemplateStatus defines the observed state
              of HCloudRemediationTemplate.
            properties:
              status:
                description: HCloudRemediationStatus defines the observed state of
                  HCloudRemediation
                properties:
                  conditions:
                    description: Conditions defines current service state of the HCloudRemediation.
                    items:
                      description: Condition defines an observation of a Cluster API
                        resource operational state.
                      properties:
                        lastTransitionTime:
                          description: Last time the condition transitioned from one
                            status to another. This should be when the underlying
                            condition changed. If that is not known, then using the
                            time when the API field changed is acceptable.
                          format: date-time
                          type: string
                        message:
                          description: A human readable message indicating details
                            about the transition. This field may be empty.
                          type: string
                        reason:
                          description: The reason for the condition's last transition
                            in CamelCase. The specific API may choose whether or not
                            this field is considered a guaranteed API. This field
                            may not be empty.
                          type: string
                        severity:
                          description: Severity provides an explicit classification
                            of Reason code, so the users or machines can immediately
                            understand the current situation and act accordingly.
                            The Severity field MUST be set only when Status=False.
                          type: string
                        status:
                          description: Status of the condition, one of True, False,
                            Unknown.
                          type: string
                        type:
                          description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                            Many .condition.type values are consistent across resources
                            like Available, but because arbitrary conditions can be
                            useful (see .node.status.conditions), the ability to deconflict
                            is important.
                          type: string
                      required:
                      - lastTransitionTime
                      - status
                      - type
                      type: object
                    type: array
                  lastRemediated:
                    description: LastRemediated identifies when the host was last
                      remediated
                    format: date-time
                    type: string
                  phase:
                    description: Phase represents the current phase of machine remediation.
                      E.g. Pending, Running, Done etc.
                    type: string
                  retryCount:
                    description: RetryCount can be used as a counter during the remediation.
                      Field can hold number of reboots etc.
                    type: integer
                type: object
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
