---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: hetznerbaremetalmachines.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: HetznerBareMetalMachine
    listKind: HetznerBareMetalMachineList
    plural: hetznerbaremetalmachines
    shortNames:
    - hbm
    - hbmachine
    - hbmachines
    - hetznerbaremetalm
    - hetznerbaremetalmachine
    singular: hetznerbaremetalmachine
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Time duration since creation of hetznerbaremetalmachine
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Provider ID
      jsonPath: .spec.providerID
      name: ProviderID
      type: string
    - description: hetznerbaremetalmachine is Ready
      jsonPath: .status.ready
      name: Ready
      type: string
    - description: Cluster to which this M3Machine belongs
      jsonPath: .metadata.labels.cluster\.x-k8s\.io/cluster-name
      name: Cluster
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: HetznerBareMetalMachine is the Schema for the hetznerbaremetalmachines
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HetznerBareMetalMachineSpec defines the desired state of
              HetznerBareMetalMachine.
            properties:
              hostSelector:
                description: HostSelector specifies matching criteria for labels on
                  HetznerBareMetalHosts. This is used to limit the set of HetznerBareMetalHost
                  objects considered for claiming for a HetznerBareMetalMachine.
                properties:
                  matchExpressions:
                    description: Label match expressions that must be true on a chosen
                      BareMetalHost
                    items:
                      description: HostSelectorRequirement defines a requirement used
                        for MatchExpressions to select host machines.
                      properties:
                        key:
                          type: string
                        operator:
                          description: Operator represents a key/field's relationship
                            to value(s). See labels.Requirement and fields.Requirement
                            for more details.
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      - values
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: Key/value pairs of labels that must exist on a chosen
                      BareMetalHost
                    type: object
                type: object
              installImage:
                description: InstallImage is the configuration which is used for the
                  autosetup configuration for installing an OS via InstallImage.
                properties:
                  btrfsDefinitions:
                    description: BTRFSDefinitions defines the btrfs subvolume definitions
                      to be created.
                    items:
                      description: BTRFSDefinition defines the btrfs subvolume definitions
                        to be created.
                      properties:
                        mount:
                          description: Mount defines the mountpath.
                          type: string
                        subvolume:
                          description: SubVolume defines the subvolume name.
                          type: string
                        volume:
                          description: Volume defines the btrfs volume name.
                          type: string
                      required:
                      - mount
                      - subvolume
                      - volume
                      type: object
                    type: array
                  image:
                    description: Image is the image to be provisioned.
                    properties:
                      name:
                        description: Name defines the archive name after download.
                          This has to be a valid name for Installimage.
                        type: string
                      path:
                        description: Path is the local path for a preinstalled image
                          from upstream.
                        type: string
                      url:
                        description: URL defines the remote URL for downloading a
                          tar, tar.gz, tar.bz, tar.bz2, tar.xz, tgz, tbz, txz image.
                        type: string
                    type: object
                  logicalVolumeDefinitions:
                    description: LVMDefinitions defines the logical volume definitions
                      to be created.
                    items:
                      description: LVMDefinition defines the logical volume definitions
                        to be created.
                      properties:
                        filesystem:
                          description: FileSystem defines the filesystem for this
                            logical volume.
                          type: string
                        mount:
                          description: Mount defines the mountpath.
                          type: string
                        name:
                          description: Name defines the volume name.
                          type: string
                        size:
                          description: Size defines the size in M/G/T or MiB/GiB/TiB.
                          type: string
                        vg:
                          description: VG defines the vg name.
                          type: string
                      required:
                      - filesystem
                      - mount
                      - name
                      - size
                      - vg
                      type: object
                    type: array
                  partitions:
                    description: Partitions defines the additional Partitions to be
                      created.
                    items:
                      description: Partition defines the additional Partitions to
                        be created.
                      properties:
                        fileSystem:
                          description: FileSystem can be ext2, ext3, ext4, btrfs,
                            reiserfs, xfs, swap or name of the LVM volume group (VG),
                            if this PART is a VG.
                          type: string
                        mount:
                          description: 'Mount defines the mount path for this filesystem.
                            or keyword ''lvm'' to use this PART as volume group (VG)
                            for LVM identifier ''btrfs.X'' to use this PART as volume
                            for btrfs subvolumes. X can be replaced with a unique
                            alphanumeric keyword. NOTE: no support btrfs multi-device
                            volumes'
                          type: string
                        size:
                          description: Size can use the keyword 'all' to assign all
                            the remaining space of the drive to the last partition.
                            can use M/G/T for unit specification in MiB/GiB/TiB
                          type: string
                      required:
                      - fileSystem
                      - mount
                      - size
                      type: object
                    type: array
                  postInstallScript:
                    description: PostInstallScript is used for configuring commands
                      which should be executed after installimage. It is passed along
                      with the installimage command.
                    type: string
                required:
                - image
                - partitions
                type: object
              providerID:
                description: ProviderID will be the hetznerbaremetalmachine in ProviderID
                  format (hcloud://<server-id>)
                type: string
              sshSpec:
                description: SSHSpec gives a reference on the secret where SSH details
                  are specified as well as ports for ssh.
                properties:
                  portAfterCloudInit:
                    description: PortAfterCloudInit specifies the port that has to
                      be used to connect to the machine after cloud init.
                    type: integer
                  portAfterInstallImage:
                    default: 22
                    description: PortAfterInstallImage specifies the port that has
                      to be used to connect to the machine after install image.
                    type: integer
                  secretRef:
                    description: SecretRef gives reference to the secret.
                    properties:
                      key:
                        description: SSHSecretKeyRef defines the key name of the SSHSecret.
                        properties:
                          name:
                            type: string
                          privateKey:
                            type: string
                          publicKey:
                            type: string
                        required:
                        - name
                        - privateKey
                        - publicKey
                        type: object
                      name:
                        type: string
                    required:
                    - key
                    - name
                    type: object
                required:
                - secretRef
                type: object
            required:
            - installImage
            type: object
          status:
            description: HetznerBareMetalMachineStatus defines the observed state
              of HetznerBareMetalMachine.
            properties:
              addresses:
                description: Addresses is a list of addresses assigned to the machine.
                  This field is copied from the infrastructure provider reference.
                items:
                  description: NodeAddress contains information for the node's address.
                  properties:
                    address:
                      description: The node address.
                      type: string
                    type:
                      description: Node address type, one of Hostname, ExternalIP
                        or InternalIP.
                      type: string
                  required:
                  - address
                  - type
                  type: object
                type: array
              conditions:
                description: Conditions defines current service state of the HetznerBareMetalMachine.
                items:
                  description: Condition defines an observation of a Cluster API resource
                    operational state.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    severity:
                      description: Severity provides an explicit classification of
                        Reason code, so the users or machines can immediately understand
                        the current situation and act accordingly. The Severity field
                        MUST be set only when Status=False.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              failureMessage:
                description: FailureMessage will be set in the event that there is
                  a terminal problem.
                type: string
              failureReason:
                description: FailureReason will be set in the event that there is
                  a terminal problem.
                type: string
              lastUpdated:
                description: LastUpdated identifies when this status was last observed.
                format: date-time
                type: string
              ready:
                description: Ready is the state of the hetznerbaremetalmachine.
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
