name: E2E Basic
on:
  workflow_dispatch:
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=sha
  registry_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-hcloud-basic:
    name: Test Hcloud Basic
    concurrency: ci-${{ github.ref }}-e2e-basic
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-basic
          e2e_make_target: test-e2e-hcloud
