name: E2E Upgrade Kubernetes
on:
  workflow_dispatch:
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=sha
  registry_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-upgrade-kubernetes:
    name: Test Kubernetes Upgrade
    concurrency: ci-${{ github.ref }}-e2e-upgrade-kubernetes
    runs-on: ubuntu-latest
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: upgrade-kubernetes
          e2e_make_target: test-e2e-upgrade-kubernetes
          e2e_tts_token: ${{ secrets.TTS_TOKEN }}
          e2e_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
