name: E2E PR Blocking
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - "releases/**"
    paths:
      - "**.go"
      - "**go.mod"
      - "**go.sum"
      - "<templates|test>/**/*.<yml|yaml>"
env:
  hcloudctl_version: 1.29.4
  IMAGE_NAME: cluster-api-provider-hetzner
  REGISTRY: quay.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=ref,event=pr

jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image
        with:
          manager_image_quay_username: ${{ secrets.QUAY_USERNAME }}
          manager_image_quay_password: ${{ secrets.QUAY_PASSWORD }}

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release
        with:
          test_release_quay_username: ${{ secrets.QUAY_USERNAME }}

  e2e-hcloud-basic:
    name: Test Hcloud Basic
    concurrency: ci-${{ github.ref }}-e2e-basic
    runs-on: ubuntu-latest
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-basic
          e2e_make_target: test-e2e
          e2e_quay_username: ${{ secrets.QUAY_USERNAME }}
          e2e_tts_token: ${{ secrets.TTS_TOKEN }}
