name: E2E PR Blocking
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - "releases/**"
    paths-ignore:
      - "**/*.md"
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=ref,event=pr
  registry_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  manager-image:
    name: Build and push manager image
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "‚ùå Skipping workflow: PR is from a fork and cannot run this workflow."
          exit 1

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syself/caph-builder:1.0.25
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      BUILD_IN_CONTAINER: "false"
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Fix broken env var HOME
        uses: ./.github/actions/fixes

      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-hcloud-basic:
    name: Test Hcloud Basic
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    concurrency: ci-${{ github.ref }}-e2e-basic
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-basic
          e2e_make_target: test-e2e-hcloud

  e2e-hetzner-basic:
    name: Test Hetzner Baremetal Basic
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    concurrency: ci-${{ github.ref }}-e2e-basic-hetzner
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run e2e Test
        id: e2e-bm
        uses: ./.github/actions/e2e
        with:
          e2e_name: hetzner-basic
          e2e_make_target: test-e2e-baremetal
          e2e_robot_user: ${{ secrets.HETZNER_ROBOT_USER }}
          e2e_robot_password: ${{ secrets.HETZNER_ROBOT_PASSWORD }}
          e2e_ssh_pub: ${{ secrets.HETZNER_SSH_PUB }}
          e2e_ssh_priv: ${{ secrets.HETZNER_SSH_PRIV }}
