name: "Lint Pull Request"
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - "**.go"
      - "**go.mod"
      - "**go.sum"
      - "<templates|test>/**/*.<yml|yaml>"
      - ".github/actions/**/*"
      - ".github/workflows/e2e-*"
      - ".github/workflows/pr-*"
      - ".golangci.yaml"
      - "images/caph/**"
      - "!**/vendor/**"
      - "test/e2e/**"
      - "docs/**"
# yamllint disable rule:line-length
jobs:
  pr-lint:
    name: "Lint Pull Request"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syself/caph-builder:1.0.25
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Verify Golang Modules
        run: make BUILD_IN_CONTAINER=false generate-modules-ci

      - name: Restore lychee cache (Link Checker)
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      # to ensure we don't miss any files that were supposed to be autogenerated.
      # if there's a diff then the workflow will exit here.
      - name: Run make verify
        run: make BUILD_IN_CONTAINER=false verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Golang Code
        run: make BUILD_IN_CONTAINER=false lint-golang-ci

      - name: Lint YAML
        run: make BUILD_IN_CONTAINER=false lint-yaml-ci
