name: "Schedule - Check links"
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
# yamllint disable rule:line-length
jobs:
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Generate Token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        id: generate-token
        with:
          app_id: ${{ secrets.SYSELF_APP_ID }}
          private_key: ${{ secrets.SYSELF_APP_PRIVATE_KEY }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@9ace499fe66cee282a29eaa628fdac2c72fa087f # v1.6.1
        id: lychee
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
        with:
          args: --config .lychee.toml ./*.md  ./docs/**/*.md
          output: ./lychee.md
          format: markdown

      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@044e1cb7e9a4dde20e22969cb67818bfca0797be # v2
        with:
          state: open
          labels: |
            link-checker

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4
        with:
          title: Link Checker Dashboard
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee.md
          token: "${{ steps.generate-token.outputs.token }}"
          labels: |
            link-checker
